OpenAPI:
  swagger_path: merceedge/tests/swagger_ref
component_template:
  paths:
  - tests/component_template
formula:
  paths:
  - tests/formula
mqtt:
  broker: mosquitto
  keepalive: 60
  port: 1883
  protocol: 3.1.1
protobuf:
  generate_code_path: merceedge/components/protobuf_gen

# provider_path: providers
provider:
  paths:
    - providers

wireload:
  paths:
  - tests/wireload
  - components
wireload_package_template: test config value
