component_template:
  paths:
    - "tests/component_template"

provider:
  paths: 
    - "providers"

wireload:
  paths: 
    - "tests/wireload"
    - "components"

formula:
  paths:
    - "tests/formula"

mqtt:
  broker: 127.0.0.1
  port: 1883
  # client_id: merceedge001
  keepalive: 60
  # username: 
  # password:
  # certificate:
  protocol: 3.1.1

OpenAPI:
  swagger_path: "merceedge/tests/swagger_ref"



protobuf:
  generate_code_path: "merceedge/components/protobuf_gen"

