provider_path: "./merceedge/providers"

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: merceedge001
  keepalive: 0
  # username: 
  # password:
  # certificate:
  protocol: 3.1.1

OpenApI:
  swagger_path: "/Users/hobo/MyProjects/MerceProject/MerceEdge/merceedge/tests/swagger"

wireload:
  path: "/Users/hobo/MyProjects/MerceProject/MerceEdge/merceedge/tests/wireload"
