provider_path: "providers"

mqtt:
  broker: 127.0.0.1
  port: 1883
  # client_id: merceedge001
  keepalive: 60
  # username: 
  # password:
  # certificate:
  protocol: 3.1.1

OpenAPI:
  swagger_path: "merceedge/tests/swagger_ref"

wireload:
  path: "tests/wireload"
